### ISSUE TITLE
About fatal error LNK1120

### ISSUE THREAD

**Issue by cainiaoshidai** [PofaixinBirusu/GLORN#1]
Hi, 
    It's a very nice work. When I compile your code, I get this error.

> 正在创建库 build\temp.win-amd64-3.7\Release\glorn/extensions/cpu/grid_subsampling\ext.lib 和对象 build\temp.win-amd64-3.7\Release\glorn/extensions/cpu/grid_subsampling\ext.exp
grid_subsampling.obj : error LNK2001: 无法解析的外部符号 "public: long * __cdecl at::TensorBase::data_ptr<long>(void)const " (??$data_ptr@J@TensorBase@at@@QEBAPEAJXZ)
 build\lib.win-amd64-3.7\glorn\ext.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe' failed with exit code 1120`
Can you give me some advice?

Thanks.
Best

**Comment by PofaixinBirusu** [comment]
Hi,
Thank you for your interest in this work. The code can't be compiled on windows system yet. According to my test with my classmates, it can be successfully compiled on the linux system. We will try to improve in the future.

**Comment by cainiaoshidai** [comment]
> Hi, Thank you for your interest in this work. The code can't be compiled on windows system yet. According to my test with my classmates, it can be successfully compiled on the linux system. We will try to improve in the future.

Thanks for your reply. I've got it.
Best.
